bonitasoft/bonita-studio

bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/ui/property/FieldDecoratorProviderTest.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/ui/property/input/ContractInputController.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/swt/rules/RealmWithDisplay.java

Some unit tests were failing due to aynchronous events and disposed display

fix unit tests with asynchronous event

---

bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/properties/AbstractBonitaDescriptionSection.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/ui/property/ContractPropertySection.java

Fix layout of contract section, in order to have table grabing in height
and width

Fix layout of contract section, in order to have table grabing in height

---

bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/properties/PropertySectionWithTabs.java

remove GridData for section created inside a TabFolder

---

bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/ContractEngineDefinitionBuilderTest.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/ContractEngineDefinitionBuilder.java

BS-13174, merge client object ComplexInput and SimpleInput

---

bundles/plugins/org.bonitasoft.studio.pagedesigner/.classpath
bundles/plugins/org.bonitasoft.studio.pagedesigner/META-INF/MANIFEST.MF
bundles/plugins/org.bonitasoft.studio.pagedesigner/build.properties
bundles/plugins/org.bonitasoft.studio.pagedesigner/pom.xml
bundles/plugins/org.bonitasoft.studio.pagedesigner/src-test/java/org/bonitasoft/studio/pagedesigner/core/converter/ToWebContractTest.java
bundles/plugins/org.bonitasoft.studio.pagedesigner/src/org/bonitasoft/studio/pagedesigner/core/converter/ToWebContract.java
bundles/plugins/org.bonitasoft.studio.pagedesigner/src/org/bonitasoft/studio/pagedesigner/core/operation/CreateFormFromContractOperation.java

update naming + dependency version

update ui designer to last Milestone

---

bundles/plugins/org.bonitasoft.studio.common.diagram/src/org/bonitasoft/studio/common/diagram/refactoring/RemoveWidgetReferencesOperation.java
bundles/plugins/org.bonitasoft.studio.common.diagram/src/org/bonitasoft/studio/common/diagram/tools/CustomDiagramGraphicalViewerKeyHandler.java
bundles/plugins/org.bonitasoft.studio.diagram.form.custom/src/org/bonitasoft/studio/diagram/form/custom/handlers/DeleteHandler.java
tests/org.bonitasoft.studio.tests/src/org/bonitasoft/studio/tests/form/DeleteWidgetWithContextMenuIT.java

Fix test asynchronism & Use isCancelled() instead of canExecute()

Fix failing integration test

---

bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/views/BonitaPropertiesBrowserPage.java
bundles/plugins/org.bonitasoft.studio.data/src-test/java/org/bonitasoft/studio/data/ui/wizard/CreateVariableProposalListenerTest.java
bundles/plugins/org.bonitasoft.studio.diagram.custom/src-test/java/org/bonitasoft/studio/diagram/custom/part/BonitaDataPropertiesBrowserPageTest.java
bundles/plugins/org.bonitasoft.studio.diagram.custom/src/org/bonitasoft/studio/diagram/custom/part/BonitaDataPropertiesBrowserPage.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/process/builders/SendTaskBuilder.java

Fix default selection regarding selection

BS-13227 - Fix default tab selection regarding diagram selection

---

tests/org.bonitasoft.studio.swtbot.framework/src/org/bonitasoft/studio/swtbot/framework/rule/LegacySWTGefBotRule.java
tests/org.bonitasoft.studio.swtbot.framework/src/org/bonitasoft/studio/swtbot/framework/rule/SWTGefBotRule.java
tests/org.bonitasoft.studio.validators.test/src/org/bonitasoft/studio/validators/test/swtbot/SWTBotValidatorTestUtil.java
tests/org.bonitasoft.studio.validators.test/src/org/bonitasoft/studio/validators/test/swtbot/TestAddValidatorToProcessAndRun.java

Create a Legacy SWTBot rule
Update validator menu label

fix integration tests with 6.x legacy

---

bundles/plugins/org.bonitasoft.studio.console.libs/.gitignore
bundles/plugins/org.bonitasoft.studio.console.libs/pom.xml

BS-12539: update git ignore and folder to clean for bonita-home which

---

bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/process/builders/ConnectionBuilder.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/process/builders/SequenceFlowBuilder.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/process/builders/TaskBuilder.java
bundles/plugins/org.bonitasoft.studio.validation/messages.properties
bundles/plugins/org.bonitasoft.studio.validation/plugin.properties
bundles/plugins/org.bonitasoft.studio.validation/plugin.xml
bundles/plugins/org.bonitasoft.studio.validation/src-test/java/org/bonitasoft/studio/validation/constraints/process/SequenceFlowContainmentConsitencyConstraintTest.java
bundles/plugins/org.bonitasoft.studio.validation/src/org/bonitasoft/studio/validation/constraints/process/SequenceFlowContainmentConsitencyConstraint.java
bundles/plugins/org.bonitasoft.studio.validation/src/org/bonitasoft/studio/validation/i18n/Messages.java

Add a validation constraint to help the user to fix its corrupted
diagram

BS-13205 NPE while trying to run imported 6.2.2 diagram in 6.4.x or above

---

bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/SimpleFieldToContractInputMappingTest.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/FieldToContractInputMapping.java

init multiple and mandatory input fields

BS-13234 generate input contract from selected business data field

---

bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/ui/property/input/edit/InputNameObservableEditingSupportTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/ui/property/input/labelProvider/InputNameCellLabelProviderTest.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/ui/property/constraint/labelProvider/ConstraintNameCellLabelProvider.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/ui/property/input/edit/InputNameObservableEditingSupport.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/ui/property/input/labelProvider/InputNameCellLabelProvider.java

Only validate duplicate at same level
Remove icon from label provider has it trigger some label display issue (cut at the end)

Update duplicated input validation

---

bundles/plugins/org.bonitasoft.studio.common/src-test/java/org/bonitasoft/studio/common/emf/tools/ExpressionHelperTest.java
bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/emf/tools/ExpressionHelper.java
bundles/plugins/org.bonitasoft.studio.connectors/src/org/bonitasoft/studio/connectors/ui/wizard/ConnectorWizard.java
bundles/plugins/org.bonitasoft.studio.connectors/src/org/bonitasoft/studio/connectors/ui/wizard/page/DatabaseConnectorOutputWizardPage.java

done in order to have green quality for this branch for duplicated lines

factorize code

---

bundles/plugins/org.bonitasoft.studio.common/src-test/java/org/bonitasoft/studio/common/emf/tools/ModelHelperTest.java
bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/emf/tools/ModelHelper.java
bundles/plugins/org.bonitasoft.studio.data/META-INF/MANIFEST.MF
bundles/plugins/org.bonitasoft.studio.data/src-test/java/org/bonitasoft/studio/data/provider/DataExpressionProviderTest.java
bundles/plugins/org.bonitasoft.studio.data/src/org/bonitasoft/studio/data/provider/DataExpressionProvider.java
bundles/plugins/org.bonitasoft.studio.data/src/org/bonitasoft/studio/data/provider/DataExpressionProviderForOutput.java
bundles/plugins/org.bonitasoft.studio.data/src/org/bonitasoft/studio/data/ui/wizard/DataWizardPage.java
bundles/plugins/org.bonitasoft.studio.diagram.form.properties/src/org/bonitasoft/studio/properties/form/sections/actions/FormActionsPropertySection.java
bundles/plugins/org.bonitasoft.studio.diagram.form.properties/src/org/bonitasoft/studio/properties/form/sections/actions/contributions/OutputSectionContribution.java
bundles/plugins/org.bonitasoft.studio.engine/src-test/java/org/bonitasoft/studio/engine/export/expression/converter/comparison/ComparisonExpressionConverterTest.java
bundles/plugins/org.bonitasoft.studio.engine/src-test/java/org/bonitasoft/studio/engine/export/expression/converter/comparison/ExpressionConditionModelSwitchTest.java
bundles/plugins/org.bonitasoft.studio.properties/src-test/java/org/bonitasoft/studio/properties/sections/forms/wizard/provider/ReadOnlyCheckboxLabelProviderTest.java
bundles/plugins/org.bonitasoft.studio.properties/src/org/bonitasoft/studio/properties/sections/forms/wizard/SelectFormWizard.java
bundles/plugins/org.bonitasoft.studio.properties/src/org/bonitasoft/studio/properties/sections/iteration/IterationPropertySection.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/process/builders/BooleanDataTypeBuilder.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/process/builders/DateDataTypeBuilder.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/process/builders/DoubleDataTypeBuilder.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/process/builders/IntegerDataTypeBuilder.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/process/builders/JavaDataTypeBuilder.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/process/builders/LongDataTypeBuilder.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/process/builders/MainProcessBuilder.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/process/builders/PoolBuilder.java

merge with https://github.com/bonitasoft/bonita-studio-sp/pull/12

BS-12883 datatypes scope in connector wizard

---

tests/org.bonitasoft.studio.configuration.test/src/org/bonitasoft/studio/configuration/test/swtbot/TestConfigurationDialog.java
tests/org.bonitasoft.studio.configuration.test/src/org/bonitasoft/studio/configuration/test/swtbot/TestProcessDependencies.java
tests/org.bonitasoft.studio.connectors.test/src/org/bonitasoft/studio/connectors/test/TestTestWSConnector.java
tests/org.bonitasoft.studio.diagram.test/src/org/bonitasoft/studio/commands/test/CopyPasteTests.java
tests/org.bonitasoft.studio.diagram.test/src/org/bonitasoft/studio/commands/test/DeleteCommandTest.java
tests/org.bonitasoft.studio.diagram.test/src/org/bonitasoft/studio/commands/test/ExtractAsSubprocessTest.java
tests/org.bonitasoft.studio.exporter.tests/src/org/bonitasoft/studio/exporter/tests/bpmn/BPMNConnectorExportImportTest.java
tests/org.bonitasoft.studio.exporter.tests/src/org/bonitasoft/studio/exporter/tests/bpmn/BPMNEventSubProcessExportImportTest.java
tests/org.bonitasoft.studio.exporter.tests/src/org/bonitasoft/studio/exporter/tests/bpmn/BPMNExportImportDataMappingTest.java
tests/org.bonitasoft.studio.exporter.tests/src/org/bonitasoft/studio/exporter/tests/bpmn/BPMNExportImportMessageDataTest.java
tests/org.bonitasoft.studio.exporter.tests/src/org/bonitasoft/studio/exporter/tests/bpmn/BPMNExportTests.java
tests/org.bonitasoft.studio.exporter.tests/src/org/bonitasoft/studio/exporter/tests/bpmn/BPMNGatewayExportImportTest.java
tests/org.bonitasoft.studio.exporter.tests/src/org/bonitasoft/studio/exporter/tests/bpmn/BPMNSequenceFlowDefaultFlowExportImportTest.java
tests/org.bonitasoft.studio.properties.test/src/org/bonitasoft/studio/properties/test/TestDecisionTable.java
tests/org.bonitasoft.studio.properties.test/src/org/bonitasoft/studio/properties/test/TestResources.java
tests/org.bonitasoft.studio.properties.test/src/org/bonitasoft/studio/properties/test/TestThrowCatchMessage.java
tests/org.bonitasoft.studio.test.swtbot.util/src/org/bonitasoft/studio/test/swtbot/util/SWTBotTestUtil.java
tests/org.bonitasoft.studio.tests/src/org/bonitasoft/studio/tests/data/DataWizardIT.java
tests/org.bonitasoft.studio.tests/src/org/bonitasoft/studio/tests/debug/TestDebugFeature.java
tests/org.bonitasoft.studio.tests/src/org/bonitasoft/studio/tests/dialog/TestDuplicate.java
tests/org.bonitasoft.studio.tests/src/org/bonitasoft/studio/tests/document/TestRunWithDocument.java
tests/org.bonitasoft.studio.tests/src/org/bonitasoft/studio/tests/timer/TestTimer.java

with the commit containing th eextraction of the constants

BS-13311: extract constant to factorize code

---

bundles/plugins/org.bonitasoft.studio.data/src/org/bonitasoft/studio/data/provider/JavaExpressionEditor.java
bundles/plugins/org.bonitasoft.studio.expression.editor/src-test/java/org/bonitasoft/studio/expression/editor/filter/ExpressionReturnTypeFilterTest.java
bundles/plugins/org.bonitasoft.studio.expression.editor/src/org/bonitasoft/studio/expression/editor/filter/ExpressionReturnTypeFilter.java
bundles/plugins/org.bonitasoft.studio.expression.editor/src/org/bonitasoft/studio/expression/editor/provider/SelectionAwareExpressionEditor.java
bundles/plugins/org.bonitasoft.studio.expression.editor/src/org/bonitasoft/studio/expression/editor/viewer/ExpressionViewer.java

Fix typo + add some validation + filter unrelevant method in java method tree

BS-13353 Fix return type compatibility evaluation

---

bundles/plugins/org.bonitasoft.studio.designer/pom.xml

BS-13307 Update artifactId of ui designer model

---

bundles/plugins/org.bonitasoft.studio.common.repository/src-test/java/org/bonitasoft/studio/common/repository/ui/viewer/CheckboxRepositoryTreeViewerTest.java
bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/ui/viewer/CheckboxRepositoryTreeViewer.java
bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/ui/viewer/FileStoreObservableFactory.java
bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/ui/viewer/FileStoreTreeStructureAdvisor.java
bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/ui/viewer/RepositoryTreeContentProvider.java
bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/ui/wizard/ExportRepositoryWizard.java
bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/ui/wizard/ExportRepositoryWizardPage.java
bundles/plugins/org.bonitasoft.studio.exporter/src/org/bonitasoft/studio/exporter/handler/ExportBosArchiveHandler.java

https://github.com/bonitasoft/bonita-studio-sp/pull/25

BS-13373 Artefact selection at export

---

bundles/plugins/org.bonitasoft.studio.validation/messages.properties
bundles/plugins/org.bonitasoft.studio.validation/plugin.xml
bundles/plugins/org.bonitasoft.studio.validation/src-test/java/org/bonitasoft/studio/validation/constraints/process/InternalFormMappingConstraintTest.java
bundles/plugins/org.bonitasoft.studio.validation/src/org/bonitasoft/studio/validation/constraints/process/InternalFormMappingConstraint.java
bundles/plugins/org.bonitasoft.studio.validation/src/org/bonitasoft/studio/validation/i18n/Messages.java

form if no target form is defined

Add a constraint that explain that studio use a fallback autogenerated

---

bundles/plugins/org.bonitasoft.studio.common.repository/src-test/java/org/bonitasoft/studio/common/repository/ui/viewer/RepositoryTreeContentProviderTest.java

Only return exportable children

BS-13332 Fix unit tests

---

bundles/plugins/org.bonitasoft.studio.designer/.classpath
bundles/plugins/org.bonitasoft.studio.designer/META-INF/MANIFEST.MF
bundles/plugins/org.bonitasoft.studio.designer/build.properties

update .classpath, MANIFEST.MF and build.properties with new jar name

BS-13307 update new jar name

---

bundles/plugins/org.bonitasoft.studio.common.diagram/src/org/bonitasoft/studio/common/gmf/tools/tree/selection/provider/process/FormMappingTabbedPropertyProvider.java
bundles/plugins/org.bonitasoft.studio.model.edit.custom/src-test/java/org/bonitasoft/studio/model/edit/custom/process/CustomFormMappingItemProviderTest.java
bundles/plugins/org.bonitasoft.studio.model.edit.custom/src/org/bonitasoft/studio/model/edit/custom/process/CustomFormMappingItemProvider.java

target form expression is refreshed in tree view when renaming form in
UI designer

BS-13192 Refresh target form name

---

tests/org.bonitasoft.studio.swtbot.framework/src/org/bonitasoft/studio/swtbot/framework/diagram/general/form/data/BotDataFormPropertySection.java
tests/org.bonitasoft.studio.tests/src/org/bonitasoft/studio/tests/iteration/MultiInstantiationIT.java
tests/org.bonitasoft.studio.tests/src/org/bonitasoft/studio/tests/refactoring/widget/RefactorWidgetIT.java

Fix unstable tests, remove deprecated methods in our own swtbot

---

bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/ui/property/input/ContractInputControllerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/ui/property/input/ContractInputController.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/ui/property/input/edit/ContractInputTypeEditingSupport.java

Fix npe when select contract input type
improve display performance

BS-13458 NPE when adding an input of type file on a process

---

bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/properties/AbstractBonitaDescriptionSection.java
bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/properties/TogglePropertyHelpContributionItem.java
bundles/plugins/org.bonitasoft.studio.contract/messages.properties
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/ui/property/ContractPropertySectionTest.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/i18n/Messages.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/ui/property/ContractPropertySection.java

allow to change section description according to the section context
change contract description

BS-13466 Guidance in Studio

---

tests/org.bonitasoft.studio.swtbot.framework/src/org/bonitasoft/studio/swtbot/framework/BotQAUtil.java

recurring failing test on slow machine

Improve feedback when failure occurs in order to understand unstable

---

bundles/plugins/org.bonitasoft.studio.businessobject/src/org/bonitasoft/studio/businessobject/ui/wizard/BusinessObjectDataWizardPage.java
bundles/plugins/org.bonitasoft.studio.common.diagram/src/org/bonitasoft/studio/common/gmf/tools/tree/selection/TabbedPropertySelectionProviderRegistry.java
bundles/plugins/org.bonitasoft.studio.common.diagram/src/org/bonitasoft/studio/common/gmf/tools/tree/selection/provider/process/OperationTabbedPropertyProvider.java
bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/ui/property/section/control/FormReferenceExpressionViewer.java
bundles/plugins/org.bonitasoft.studio.expression.editor/src/org/bonitasoft/studio/expression/editor/operation/OperationViewer.java
bundles/plugins/org.bonitasoft.studio.expression.editor/src/org/bonitasoft/studio/expression/editor/viewer/EditExpressionDialog.java
bundles/plugins/org.bonitasoft.studio.expression.editor/src/org/bonitasoft/studio/expression/editor/viewer/ExpressionViewer.java
bundles/plugins/org.bonitasoft.studio.expression.editor/src/org/bonitasoft/studio/expression/editor/viewer/GroovyOnlyExpressionViewer.java
bundles/plugins/org.bonitasoft.studio.scripting/src/org/bonitasoft/studio/scripting/provider/ScriptExpressionEditor.java

use a default expression return type

BS-13288 Use a default expression return type

---

bundles/plugins/org.bonitasoft.studio.common/src-test/java/org/bonitasoft/studio/common/properties/PropertySectionHistoryTest.java
bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/properties/AbstractBonitaDescriptionSection.java
bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/properties/PropertySectionHistory.java
bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/properties/TogglePropertyHelpContributionItem.java

Show contextual help by defaut on pre definied section
Store description visibility.

BS-13471 Show contextual help by defaut on pre definied sectionShow contextual help by defaut on pre definied section

---

bundles/plugins/org.bonitasoft.studio.engine/src-test/java/org/bonitasoft/studio/engine/TomcatVmArgsBuilderTest.java
bundles/plugins/org.bonitasoft.studio.engine/src/org/bonitasoft/studio/engine/BOSWebServerManager.java
bundles/plugins/org.bonitasoft.studio.engine/src/org/bonitasoft/studio/engine/TomcatVmArgsBuilder.java

BS-13535: add a system property to Tomcat in order to allow (or not) it

---

bundles/plugins/org.bonitasoft.studio.engine/src/org/bonitasoft/studio/engine/operation/DeployProcessOperation.java

is not providing any known problem

Log stackstrace when the engine was not able to enable the process but

---

bundles/plugins/org.bonitasoft.studio.application/messages.properties
bundles/plugins/org.bonitasoft.studio.application/src/org/bonitasoft/studio/application/BonitaStudioWorkbenchWindowAdvisor.java
bundles/plugins/org.bonitasoft.studio.application/src/org/bonitasoft/studio/application/dialog/ExitDialog.java
bundles/plugins/org.bonitasoft.studio.application/src/org/bonitasoft/studio/application/i18n/Messages.java
bundles/plugins/org.bonitasoft.studio.common/messages.properties
bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/Messages.java

BS-13526 Prompt warning when closing studio

---

bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/jface/SWTBotConstants.java
tests/org.bonitasoft.studio.connectors.test/src/org/bonitasoft/studio/connectors/test/database/TestDatabaseConnectorOutputMode.java
tests/org.bonitasoft.studio.connectors.test/src/org/bonitasoft/studio/connectors/test/swtbot/TestLoadSaveConnectorConfiguration.java
tests/org.bonitasoft.studio.connectors.test/src/org/bonitasoft/studio/connectors/test/swtbot/TestTextAreaInConnectorWizard.java
tests/org.bonitasoft.studio.diagram.test/src/org/bonitasoft/studio/diagram/test/DiagramTests.java
tests/org.bonitasoft.studio.expressions.test/src/org/bonitasoft/expressions/test/TestPatternExpressionViewer.java
tests/org.bonitasoft.studio.properties.test/src/org/bonitasoft/studio/properties/test/TestConditionExpression.java
tests/org.bonitasoft.studio.tests/src/org/bonitasoft/studio/tests/data/DataWizardIT.java

BS-13254: do minimal update for data conversion into variable - update

---

bundles/plugins/org.bonitasoft.studio-models/process.ecore
bundles/plugins/org.bonitasoft.studio-models/process.genmodel
bundles/plugins/org.bonitasoft.studio-models/process.history
bundles/plugins/org.bonitasoft.studio.businessobject/src-test/java/org/bonitasoft/studio/businessobject/ui/wizard/editingsupport/FieldTypeEditingSupportTest.java
bundles/plugins/org.bonitasoft.studio.businessobject/src/org/bonitasoft/studio/businessobject/ui/wizard/editingsupport/FieldTypeEditingSupport.java
bundles/plugins/org.bonitasoft.studio.common/src-test/java/org/bonitasoft/studio/common/emf/tools/ExpressionHelperTest.java
bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/ModelVersion.java
bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/emf/tools/ExpressionHelper.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/ui/property/input/ContractInputTreeViewer.java
bundles/plugins/org.bonitasoft.studio.data/src/org/bonitasoft/studio/data/ui/wizard/DataWizardPage.java
bundles/plugins/org.bonitasoft.studio.model.edit.custom/src-test/java/org/bonitasoft/studio/model/edit/custom/process/CustomContractInputItemProviderTest.java
bundles/plugins/org.bonitasoft.studio.model.edit.custom/src/org/bonitasoft/studio/model/edit/custom/process/CustomContractInputItemProvider.java
bundles/plugins/org.bonitasoft.studio.model.edit.custom/src/org/bonitasoft/studio/model/edit/custom/process/CustomProcessItemProviderAdapterFactory.java

Order datatypes in lists
Display java type next to contract input type

BS-13279 Order datatypes in lists

---

bundles/plugins/org.bonitasoft.studio.document/src-test/java/org/bonitasoft/studio/document/ui/control/MultipleFileContractInputSelectionCompositeTest.java
bundles/plugins/org.bonitasoft.studio.document/src-test/java/org/bonitasoft/studio/document/ui/control/SingleFileContractInputSelectionCompositeTest.java
bundles/plugins/org.bonitasoft.studio.document/src-test/java/org/bonitasoft/studio/document/ui/validator/MultipleContractInputValidatorTest.java
bundles/plugins/org.bonitasoft.studio.document/src-test/java/org/bonitasoft/studio/document/ui/validator/SingleContractInputValidatorTest.java
bundles/plugins/org.bonitasoft.studio.document/src/org/bonitasoft/studio/document/ui/DocumentPropertySection.java
bundles/plugins/org.bonitasoft.studio.document/src/org/bonitasoft/studio/document/ui/DocumentWizardPage.java
bundles/plugins/org.bonitasoft.studio.document/src/org/bonitasoft/studio/document/ui/control/FileContractInputSelectionComposite.java
bundles/plugins/org.bonitasoft.studio.document/src/org/bonitasoft/studio/document/ui/control/MultipleFileContractInputSelectionComposite.java
bundles/plugins/org.bonitasoft.studio.document/src/org/bonitasoft/studio/document/ui/control/SingleFileContractInputSelectionComposite.java
bundles/plugins/org.bonitasoft.studio.document/src/org/bonitasoft/studio/document/ui/validator/ContractInputValidator.java
bundles/plugins/org.bonitasoft.studio.document/src/org/bonitasoft/studio/document/ui/validator/MultipleContractInputValidator.java
bundles/plugins/org.bonitasoft.studio.document/src/org/bonitasoft/studio/document/ui/validator/SingleContractInputValidator.java

Split single and multiple document validator

Fix document validation

---

bundles/plugins/org.bonitasoft.studio.designer/src-test/java/org/bonitasoft/studio/designer/core/PageDesignerURLFactoryTest.java
bundles/plugins/org.bonitasoft.studio.designer/src-test/java/org/bonitasoft/studio/designer/core/converter/ToWebContractTest.java
bundles/plugins/org.bonitasoft.studio.designer/src-test/java/org/bonitasoft/studio/designer/core/expression/CreateNewFormProposalListenerTest.java
bundles/plugins/org.bonitasoft.studio.designer/src-test/java/org/bonitasoft/studio/designer/ui/property/section/control/CreateOrEditFormProposalListenerTest.java
bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/core/FormScope.java
bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/core/PageDesignerURLFactory.java
bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/core/converter/ToWebContract.java
bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/core/expression/CreateNewFormProposalListener.java
bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/core/operation/CreateFormFromContractOperation.java
bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/ui/property/section/control/CreateOrEditFormProposalListener.java
pom.xml

https://github.com/bonitasoft/bonita-studio-sp/pull/37

integrate M22 milestone

---

bundles/plugins/org.bonitasoft.studio.engine/src/org/bonitasoft/studio/engine/BOSWebServerManager.java

Fix Clean on Shutdown: bonita hoem structure update and inlusion of

---

bundles/plugins/org.bonitasoft.studio.designer/src-test/java/org/bonitasoft/studio/designer/core/PageDesignerURLFactoryTest.java
bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/core/PageDesignerURLFactory.java

Use /home at the end of UI Designer URl in order to have language

---

bundles/plugins/org.bonitasoft.studio.designer/messages.properties
bundles/plugins/org.bonitasoft.studio.designer/src-test/java/org/bonitasoft/studio/designer/ui/contribution/OpenUIDesignerCoolBarItemTest.java
bundles/plugins/org.bonitasoft.studio.designer/src-test/java/org/bonitasoft/studio/designer/ui/handler/OpenUIDesignerHandlerTest.java
bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/i18n/Messages.java
bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/ui/contribution/OpenUIDesignerCoolBarItem.java
bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/ui/handler/OpenUIDesignerHandler.java

BS-13453: open information dialog when clicking on UI designer in

---

bundles/plugins/org.bonitasoft.studio.designer/messages.properties
bundles/plugins/org.bonitasoft.studio.designer/src-test/java/org/bonitasoft/studio/designer/ui/contribution/CreateAndEditFormContributionItemTest.java
bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/i18n/Messages.java
bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/ui/contribution/CreateAndEditFormContributionItem.java

on the UI designer button, I need a warning
add a popup when there is no contract input and form does not exist.
add tests

BS-13505 As Dave, when my contract is empty (pool and task) and I click

---

bundles/plugins/org.bonitasoft.studio.application/META-INF/MANIFEST.MF
bundles/plugins/org.bonitasoft.studio.application/src/org/bonitasoft/studio/application/BonitaStudioWorkbenchAdvisor.java

Fix contract input performance issue on second add
preload svg figures

BS-13589 Performance improvement

---

bundles/plugins/org.bonitasoft.studio.validation/src/org/bonitasoft/studio/validation/constraints/process/FormMappingConstraint.java

Replace == with Objects.equals()

BS-13069 Fix duplicated name constraint

---

bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/process/builders/SubProcessEventBuilder.java
bundles/plugins/org.bonitasoft.studio.validation/src-test/java/org/bonitasoft/studio/validation/constraints/process/StartEventWithContractConstraintTest.java
bundles/plugins/org.bonitasoft.studio.validation/src/org/bonitasoft/studio/validation/constraints/process/StartEventWithContractConstraint.java

Handle subprocess event use case

BS-13711 Handle subprocess event use case

---

bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/form/builders/WidgetBuilder.java
bundles/plugins/org.bonitasoft.studio.validation/src-test/java/org/bonitasoft/studio/validation/constraints/process/ValidableOperationTest.java
bundles/plugins/org.bonitasoft.studio.validation/src/org/bonitasoft/studio/validation/constraints/process/JavaSetterOperatorConstraint.java
bundles/plugins/org.bonitasoft.studio.validation/src/org/bonitasoft/studio/validation/constraints/process/OpeartionReturnTypeWarningConstraint.java
bundles/plugins/org.bonitasoft.studio.validation/src/org/bonitasoft/studio/validation/constraints/process/OperationLeftOperandConsistencyConstraint.java
bundles/plugins/org.bonitasoft.studio.validation/src/org/bonitasoft/studio/validation/constraints/process/ValidableOperation.java

Skip validation of output operation of readonly widgets

BS-12881 Do not validate read only widget output operations

---

bundles/plugins/org.bonitasoft.studio-models/process.history
bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/ModelVersion.java
bundles/plugins/org.bonitasoft.studio.migration/src-test/java/org/bonitasoft/studio/migration/custom/migration/form/ShapeFillColorCustomMigrationTest.java
bundles/plugins/org.bonitasoft.studio.migration/src/org/bonitasoft/studio/migration/custom/migration/form/ShapeFillColorCustomMigration.java

Remove fill color in custom migration

BS-12897 Migrate Fill color of widgets

---

bundles/plugins/org.bonitasoft.studio.engine/src/org/bonitasoft/studio/engine/BOSWebServerManager.java

Do not use a regexp to replace path in server.xml

BS-12991 Do not use a regexp to replace path in server.xml

---

bundles/plugins/org.bonitasoft.studio.exporter/src/org/bonitasoft/studio/exporter/bpmn/transfo/expression/FormalExpressionTransformer.java
bundles/plugins/org.bonitasoft.studio.importer/src-test/java/org/bonitasoft/studio/importer/bpmn/BPMNToProcTest.java
bundles/plugins/org.bonitasoft.studio.importer/src/org/bonitasoft/studio/importer/bpmn/BPMNToProc.java
bundles/plugins/org.bonitasoft.studio.importer/src/org/bonitasoft/studio/importer/builder/IProcBuilder.java
bundles/plugins/org.bonitasoft.studio.importer/src/org/bonitasoft/studio/importer/builder/ProcBuilder.java

re-import multiinstance properties from bpmn
https://github.com/bonitasoft/bonita-studio-sp/pull/47

BS-12255 import multiinstance from bpmn

---

bundles/plugins/org.bonitasoft.studio.data/messages.properties
bundles/plugins/org.bonitasoft.studio.data/src/org/bonitasoft/studio/data/i18n/Messages.java
bundles/plugins/org.bonitasoft.studio.data/src/org/bonitasoft/studio/data/ui/property/section/AbstractDataSection.java
bundles/plugins/org.bonitasoft.studio.properties.bos/src/org/bonitasoft/studio/properties/bos/sections/data/DataSectionBOS/DataSectionBOS.java
bundles/plugins/org.bonitasoft.studio.properties/src/org/bonitasoft/studio/properties/sections/transientdata/ApplicationTransientDataSection.java

Improves labels and guidance consistency
https://github.com/bonitasoft/bonita-studio-sp/pull/49

BS-12361 Fix label

---

bundles/plugins/org.bonitasoft.studio.common.diagram/META-INF/MANIFEST.MF
bundles/plugins/org.bonitasoft.studio.common.diagram/src-test/java/org/bonitasoft/studio/common/gmf/tools/tree/selection/RefreshPropertyViewsSelectionTest.java
bundles/plugins/org.bonitasoft.studio.common.diagram/src-test/java/org/bonitasoft/studio/common/gmf/tools/tree/selection/TabbedPropertySynchronizerListenerTest.java
bundles/plugins/org.bonitasoft.studio.common.diagram/src/org/bonitasoft/studio/common/gmf/tools/tree/selection/RefreshPropertyViewsSelection.java
bundles/plugins/org.bonitasoft.studio.common.diagram/src/org/bonitasoft/studio/common/gmf/tools/tree/selection/TabbedPropertySynchronizerListener.java

Refresh all property views when update from tree view

BS-13729 Update property view selection

---

bundles/plugins/org.bonitasoft.studio.diagram.custom/src/org/bonitasoft/studio/diagram/custom/parts/CustomPoolCompartmentEditPart.java
tests/org.bonitasoft.studio.diagram.test/src/org/bonitasoft/studio/diagram/test/DiagramTests.java

Fix undo/redo when add/remove a lane
Fix classcast exception when found edit part was LaneNameEditPart and not LaneEditPart

BS-13739 Undo/Redo Lane creation

---

bundles/plugins/org.bonitasoft.studio.businessobject/src/org/bonitasoft/studio/businessobject/ui/wizard/ManageBusinessDataModelWizard.java

BS-12767 Imrpove stack visibility

---

bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/process/builders/MainProcessBuilder.java
bundles/plugins/org.bonitasoft.studio.validation/messages.properties
bundles/plugins/org.bonitasoft.studio.validation/src-test/java/org/bonitasoft/studio/validation/constraints/process/InternalFormMappingConstraintTest.java
bundles/plugins/org.bonitasoft.studio.validation/src/org/bonitasoft/studio/validation/constraints/process/InternalFormMappingConstraint.java
bundles/plugins/org.bonitasoft.studio.validation/src/org/bonitasoft/studio/validation/i18n/Messages.java

when Form Mapping are defined at diagram level.

BS-13742: add a validation message to warn user about model inconsitency

---

bundles/plugins/org.bonitasoft.studio.document/src-test/java/org/bonitasoft/studio/document/ui/DocumentWizardPageTest.java
bundles/plugins/org.bonitasoft.studio.document/src/org/bonitasoft/studio/document/ui/DocumentWizardPage.java

BS-13736: update correctly enablement state of Mime Type on edition of a

---

bundles/plugins/org.bonitasoft.studio.document/src-test/java/org/bonitasoft/studio/document/core/export/MultipleDocumentEngineDefinitionBuilderTest.java
bundles/plugins/org.bonitasoft.studio.document/src/org/bonitasoft/studio/document/core/export/MultipleDocumentEngineDefinitionBuilder.java
bundles/plugins/org.bonitasoft.studio.document/src/org/bonitasoft/studio/document/ui/DocumentWizardPage.java

Add None option for multiple document initial value

BS-13675 none option

---

bundles/plugins/org.bonitasoft.studio.importer.bar/messages.properties
bundles/plugins/org.bonitasoft.studio.importer.bar/src/org/bonitasoft/studio/importer/bar/custom/migration/ConnectorMigration.java
bundles/plugins/org.bonitasoft.studio.importer.bar/src/org/bonitasoft/studio/importer/bar/custom/migration/WidgetMigration.java
bundles/plugins/org.bonitasoft.studio.importer.bar/src/org/bonitasoft/studio/importer/bar/custom/migration/connector/mapper/ConnectorDescriptorToConnectorDefinition.java
bundles/plugins/org.bonitasoft.studio.importer.bar/src/org/bonitasoft/studio/importer/bar/i18n/Messages.java
bundles/plugins/org.bonitasoft.studio.migration/src/org/bonitasoft/studio/migration/ui/action/ToggleLinkingAction.java
tests/org.bonitasoft.studio.importer.bar.tests/META-INF/MANIFEST.MF
tests/org.bonitasoft.studio.importer.bar.tests/src/org/bonitasoft/studio/importer/bar/tests/TestSimpleMigrationUseCase.java

- BS-12595 
Sometimes widget uuid appears to be null. It leads to some missing element after migration. Force a UUID in those cases 
- BS-12321 
Add FORM_FIELD expression in left operand of output operations + fix test case 
- BS-13106 
ix npe when replacing translations key in a v5 connector

BS-12595 5.x import

---

bundles/plugins/org.bonitasoft.studio.diagram.custom/src/org/bonitasoft/studio/diagram/custom/commands/NewDiagramCommandHandler.java
bundles/plugins/org.bonitasoft.studio.diagram.custom/src/org/bonitasoft/studio/diagram/custom/providers/CustomProcessViewProvider.java
bundles/plugins/org.bonitasoft.studio.diagram.custom/src/org/bonitasoft/studio/diagram/custom/repository/NewDiagramFactory.java

set pool size when creating new pool

BS-12599 Element not displayed in the pool due to the pool's size

---

bundles/plugins/org.bonitasoft.studio.properties/src-test/java/org/bonitasoft/studio/properties/sections/forms/wizard/SelectGeneratedWidgetsWizardPageTest.java
bundles/plugins/org.bonitasoft.studio.properties/src/org/bonitasoft/studio/properties/sections/forms/wizard/SelectGeneratedWidgetsWizardPage.java

Fix CheckStateProvider for widget mapping tree

BS-13756 Fix CheckStateProvider for widget mapping tree

---

bundles/plugins/org.bonitasoft.studio.expression.editor/src-test/java/org/bonitasoft/studio/expression/editor/operation/OperationViewerTest.java
bundles/plugins/org.bonitasoft.studio.expression.editor/src/org/bonitasoft/studio/expression/editor/operation/OperationViewer.java
bundles/plugins/org.bonitasoft.studio.expression.editor/src/org/bonitasoft/studio/expression/editor/viewer/ExpressionViewer.java

Fix operator update when no editing domain set for OperationViewer

BS-13759 Fix operator update

---

bundles/plugins/org.bonitasoft.studio.common.diagram/src/org/bonitasoft/studio/common/gmf/tools/tree/MainProcessFormMappingViewerFilter.java

Always show Form Mapping in Tree view

BS-13727 Always display Form Mapping in Tree view

---

bundles/plugins/org.bonitasoft.studio.designer/messages.properties
bundles/plugins/org.bonitasoft.studio.designer/src-test/java/org/bonitasoft/studio/designer/ui/handler/OpenUIDesignerHandlerTest.java
bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/i18n/Messages.java
bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/ui/handler/OpenUIDesignerHandler.java

Wait for tomcat server when opening ui designer

BS-13766 Wait for tomcat server when opening ui designer

---

bundles/plugins/org.bonitasoft.studio.groovy/scripts/BonitaXML.groovy

BonitaXML.evaluateOnXpathVariable

BS-12075: add Javadoc on provided groovy scripts

---

bundles/plugins/org.bonitasoft.studio.designer/META-INF/MANIFEST.MF
bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/ui/contribution/OpenUIDesignerCoolBarItem.java
bundles/plugins/org.bonitasoft.studio.profiles/plugin.xml

Activity Category in order to hide them by default on Businesss Analyst
profile

BS-13706: put Data and execution views and UI designer menu in correct

---

bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/RelationFieldToContractInputMappingTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/RootContractInputGeneratorTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/SimpleFieldToContractInputMappingTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/BusinessObjectInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/CompositionReferencePropertyInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/SimpleFieldPropertyInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/FieldToContractInputMapping.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/RelationFieldToContractInputMapping.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/RootContractInputGenerator.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/SimpleFieldToContractInputMapping.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/SimpleFieldPropertyInitializer.java

Support multiple primitive type fields when generating contract mapping
operations

BS-13818 Support multiple primitive type fields

---

bundles/plugins/org.bonitasoft.studio.engine/src-test/java/org/bonitasoft/studio/engine/export/builder/EngineFlowElementBuilderTest.java
bundles/plugins/org.bonitasoft.studio.engine/src/org/bonitasoft/studio/engine/export/builder/AbstractProcessBuilder.java

change type of exported expression from BusinessObjectData to
BusinessObjectDataReference

BS-13763 Missing iterator data in context REST API response

---

bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/functions/ContractInputFunctions.java
bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/predicate/ContractInputPredicates.java
bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/predicate/ExpressionPredicates.java
bundles/plugins/org.bonitasoft.studio.contract/META-INF/MANIFEST.MF
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/MappingOperationScriptBuilderTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/BusinessObjectInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/BusinessObjectListInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/CompositionReferencePropertyInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleCompositionReferencePropertyInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/PropertyInitializerFactoryTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/SimpleFieldPropertyInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/refactoring/RefactorContractInputOperationTest.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/DefaultFormatterPreferences.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/MappingOperationScriptBuilder.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/BusinessObjectInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/BusinessObjectListInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleCompositionReferencePropertyInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/PropertyInitializerFactory.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/SimpleFieldPropertyInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/refactoring/RefactorContractInputOperation.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/ui/property/input/edit/InputNameObservableEditingSupport.java
bundles/plugins/org.bonitasoft.studio.refactoring/src/org/bonitasoft/studio/refactoring/core/AbstractRefactorOperation.java

Support multiple composed reference for operation generation

BS-13818 Support multiple composed type fields

---

bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/RootContractInputGeneratorTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/FieldToContractInputMappingOperationBuilderTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/BusinessObjectListInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/RootContractInputGenerator.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/FieldToContractInputMappingOperationBuilder.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/BusinessObjectListInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleCompositionReferencePropertyInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/ui/wizard/ContractInputGenerationWizard.java

* Handle multiple business data when generating contract from business
data
* Create a mapping operation

BS-13851 Support multiple business data

---

bundles/plugins/org.bonitasoft.studio.properties/src/org/bonitasoft/studio/properties/sections/subprocess/ParametersMappingSection.java

add a listener on list of call activity data

BS-13817 Data mapping on call activity are not up to date

---

tests/org.bonitasoft.studio.tests/src/org/bonitasoft/studio/tests/data/DataWizardIT.java

BS-13150: use data with name surely diferent to be sure no interaction

---

bundles/plugins/org.bonitasoft.studio.businessobject/src-test/java/org/bonitasoft/studio/businessobject/core/repository/BusinessObjectModelRepositoryStoreTest.java
bundles/plugins/org.bonitasoft.studio.businessobject/src/org/bonitasoft/studio/businessobject/core/operation/DeployBDMOperation.java
bundles/plugins/org.bonitasoft.studio.businessobject/src/org/bonitasoft/studio/businessobject/core/repository/BusinessObjectModelRepositoryStore.java

in headless mode (Tomcat with the engine is not started)

BS-13862: Don't deploy Business Object Definitions when application is

---

bundles/plugins/org.bonitasoft.studio.common.repository/plugin.xml
bundles/plugins/org.bonitasoft.studio.common.repository/schema/org.bonitasodt.studio.repositoryFactory.exsd
bundles/plugins/org.bonitasoft.studio.common.repository/src-test/java/org/bonitasoft/studio/common/repository/RepositoryTest.java
bundles/plugins/org.bonitasoft.studio.common.repository/src-test/java/org/bonitasoft/studio/common/repository/core/CreateBonitaBPMProjectOperationTest.java
bundles/plugins/org.bonitasoft.studio.common.repository/src-test/java/org/bonitasoft/studio/common/repository/core/ProjectClasspathFactoryTest.java
bundles/plugins/org.bonitasoft.studio.common.repository/src-test/java/org/bonitasoft/studio/common/repository/core/ProjectManifestFactoryTest.java
bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/IRepositoryFactory.java
bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/Repository.java
bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/RepositoryFactory.java
bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/RepositoryManager.java
bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/core/BonitaBPMProjectMigrationOperation.java
bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/core/CreateBonitaBPMProjectOperation.java
bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/core/ProjectClasspathFactory.java
bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/core/ProjectManifestFactory.java
bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/model/IRepository.java
bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/extension/ExtensionContextInjectionFactory.java
bundles/plugins/org.bonitasoft.studio.tests-utils/META-INF/MANIFEST.MF
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/fakes/IResourceFakesBuilder.java

* Check for .classpath and MANIFEST when opening a repository (those
files are not committed on the server)
* Use a proper design to create a repository instance in order to make
it testable (with di)
https://github.com/bonitasoft/bonita-studio-sp/pull/58

BS-13900 Repository initialization

---

bundles/plugins/org.bonitasoft.studio.groovy.ui/src-test/java/org/bonitasoft/studio/groovy/ui/job/UnknownElementsIndexerTest.java
bundles/plugins/org.bonitasoft.studio.groovy.ui/src-test/java/org/bonitasoft/studio/groovy/ui/job/VariablesVisitorTest.java
bundles/plugins/org.bonitasoft.studio.groovy.ui/src/org/bonitasoft/studio/groovy/ui/job/UnknownElementsIndexer.java
bundles/plugins/org.bonitasoft.studio.groovy.ui/src/org/bonitasoft/studio/groovy/ui/job/VariablesVisitor.java
bundles/plugins/org.bonitasoft.studio.groovy.ui/src/org/bonitasoft/studio/groovy/ui/viewer/TestGroovyScriptUtil.java

Fix false positive in varaible detection

BS-11871 Fix false positive in variable detection

---

bundles/plugins/org.bonitasoft.studio.expression.editor/src/org/bonitasoft/studio/expression/editor/viewer/ExpressionViewer.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/form/builders/FormBuilder.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/form/builders/ValidatorBuilder.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/form/builders/WidgetBuilder.java
bundles/plugins/org.bonitasoft.studio.validators/.classpath
bundles/plugins/org.bonitasoft.studio.validators/META-INF/MANIFEST.MF
bundles/plugins/org.bonitasoft.studio.validators/src-test/org/bonitasoft/studio/validators/ui/property/section/AvailableExpressionTypeFilterWitoutContingentWidgetsTest.java
bundles/plugins/org.bonitasoft.studio.validators/src/org/bonitasoft/studio/validators/ui/property/section/AvailableExpressionTypeFilterWitoutContingentWidgets.java

BS-13938: implement filter on Contingency form fields to have it working

---

bundles/plugins/org.bonitasoft.studio.common.repository/src-test/java/org/bonitasoft/studio/common/repository/RepositoryTest.java
bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/Repository.java

Do not open a repository before deletion.
Refresh before delete only if project is opened.
https://github.com/bonitasoft/bonita-studio-sp/pull/60

BS-13952 remove remote repository

---

bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/AggregationReferencePropertyInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/BusinessObjectQueryInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleAggregationReferencePropertyInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleBusinessObjectQueryInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleCompositionReferencePropertyInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/NewBusinessObjectListInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/AbstractBusinessObjectInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/BusinessObjectQueryInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleBusinessObjectQueryInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/NewBusinessObjectListInitializer.java

Add comments in generated scripts

BS-14022 Add comments in generated scripts

---

bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/RootContractInputGeneratorTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/expression/FieldToContractInputMappingExpressionBuilderTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/FieldToContractInputMappingOperationBuilderTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/MappingOperationScriptBuilderTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/NewBusinessObjectInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/ui/property/ContractPropertySectionTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/ui/wizard/ContractInputGenerationWizardTest.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/RootContractInputGenerator.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/expression/FieldToContractInputMappingExpressionBuilder.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/FieldToContractInputMappingOperationBuilder.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/CompositionReferencePropertyInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/NewBusinessObjectInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/factory/BusinessObjectInitializerFactory.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/ui/property/ContractPropertySection.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/ui/wizard/ContractInputGenerationWizard.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/ui/wizard/SelectBusinessDataWizardPage.java
bundles/plugins/org.bonitasoft.studio.data/src/org/bonitasoft/studio/data/ui/property/section/control/DataViewer.java

Generate initial value script expression

BS-14059 Generate initial value script expression

---

bundles/plugins/org.bonitasoft.studio.actors/src/org/bonitasoft/studio/actors/configuration/ActorFilterBarResourceProvider.java
bundles/plugins/org.bonitasoft.studio.connectors/src-test/java/org/bonitasoft/studio/connectors/configuration/ConnectorBarResourceProviderTest.java
bundles/plugins/org.bonitasoft.studio.connectors/src/org/bonitasoft/studio/connectors/configuration/AbstractConnectorBarResourceProvider.java
bundles/plugins/org.bonitasoft.studio.connectors/src/org/bonitasoft/studio/connectors/configuration/ConnectorBarResourceProvider.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/configuration/builders/ConfigurationBuilder.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/configuration/builders/DefinitionMappingBuilder.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/configuration/builders/FragmentBuilder.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/configuration/builders/FragmentContainerBuilder.java

Exported custom implementation jar even if source is not present.
Add unit test
Reuse the same cod between filters and connectors

BS-14002 Export custom implementation jar from dependency store

---

bundles/plugins/org.bonitasoft.studio.data/src-test/java/org/bonitasoft/studio/data/ui/wizard/DataDefaultValueExpressionFilterTest.java
bundles/plugins/org.bonitasoft.studio.data/src/org/bonitasoft/studio/data/ui/wizard/DataDefaultValueExpressionFilter.java
bundles/plugins/org.bonitasoft.studio.expression.editor/messages.properties
bundles/plugins/org.bonitasoft.studio.expression.editor/src-test/java/org/bonitasoft/studio/expression/editor/operation/OperationReturnTypesValidatorTest.java
bundles/plugins/org.bonitasoft.studio.expression.editor/src/org/bonitasoft/studio/expression/editor/i18n/Messages.java
bundles/plugins/org.bonitasoft.studio.expression.editor/src/org/bonitasoft/studio/expression/editor/operation/OperationReturnTypesValidator.java

Add a validation on operation
Remove Query type from process variables default value.

BS-12563 forbid query expression with process variables

---

bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/MappingOperationScriptBuilderTest.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/factory/AbsractInitializerFactory.java

fix wrong script generation for compososition relations

BS-14059 Generate Script when creating a process instantiation contract

---

bundles/plugins/org.bonitasoft.studio.common.diagram/.classpath
bundles/plugins/org.bonitasoft.studio.common.diagram/.settings/org.eclipse.jdt.core.prefs
bundles/plugins/org.bonitasoft.studio.common.diagram/META-INF/MANIFEST.MF
bundles/plugins/org.bonitasoft.studio.connectors.database.drivers.prop/build.properties
bundles/plugins/org.bonitasoft.studio.data/.classpath
bundles/plugins/org.bonitasoft.studio.data/.settings/org.eclipse.jdt.core.prefs
bundles/plugins/org.bonitasoft.studio.data/META-INF/MANIFEST.MF
bundles/plugins/org.bonitasoft.studio.expression.editor/.classpath
bundles/plugins/org.bonitasoft.studio.expression.editor/.settings/org.eclipse.jdt.core.prefs
bundles/plugins/org.bonitasoft.studio.expression.editor/META-INF/MANIFEST.MF
bundles/plugins/org.bonitasoft.studio.repository.themes/.classpath
bundles/plugins/org.bonitasoft.studio.repository.themes/.settings/org.eclipse.jdt.core.prefs
bundles/plugins/org.bonitasoft.studio.repository.themes/META-INF/MANIFEST.MF

Move classpath java version to 1.7

Move classpath java version to 1.7

---

bundles/plugins/org.bonitasoft.studio.businessobject/messages.properties
bundles/plugins/org.bonitasoft.studio.businessobject/src-test/java/org/bonitasoft/studio/businessobject/core/operation/DeployBDMOperationTest.java
bundles/plugins/org.bonitasoft.studio.businessobject/src/org/bonitasoft/studio/businessobject/core/operation/DeployBDMOperation.java
bundles/plugins/org.bonitasoft.studio.businessobject/src/org/bonitasoft/studio/businessobject/i18n/Messages.java
bundles/plugins/org.bonitasoft.studio.businessobject/src/org/bonitasoft/studio/businessobject/ui/wizard/ManageBusinessDataModelWizard.java

When removing all Business objects from the bdm it now delete and
uninstall the BDM instead of having a validation error.

BS-14187 enable deletion of bdm

---

bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/RelationFieldToContractInputMappingTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/RootContractInputGeneratorTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleBusinessObjectQueryInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleCompositionReferencePropertyInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/NewBusinessObjectListInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/factory/PropertyInitializerFactoryTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/factory/RelationPropertyInitializerFactoryTest.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/RootContractInputGenerator.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleBusinessObjectQueryInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleCompositionReferencePropertyInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/NewBusinessObjectListInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/factory/PropertyInitializerFactory.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/factory/RelationPropertyInitializerFactory.java

Reverts bonitasoft/bonita-studio#256

Revert "Defect/bs 14249 composition multiple for default value"

---

bundles/plugins/org.bonitasoft.studio.migration/src/org/bonitasoft/studio/migration/utils/StringToExpressionConverter.java
tests/org.bonitasoft.studio.importer.bar.tests/src/org/bonitasoft/studio/importer/bar/tests/connector/TestConnectorMigrationUseCase.java

Clean useless instances in expression referenced  EObjects

Bs-14222 connectors in forms migration

---

bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/RelationFieldToContractInputMappingTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/RootContractInputGeneratorTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/expression/FieldToContractInputMappingExpressionBuilderTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/FieldToContractInputMappingOperationBuilderTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/MappingOperationScriptBuilderTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleAggregationReferencePropertyInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleBusinessObjectQueryInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleCompositionReferencePropertyInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/NewBusinessObjectListInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/factory/BusinessObjectInitializerFactoryTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/factory/PropertyInitializerFactoryTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/factory/RelationPropertyInitializerFactoryTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/ui/wizard/ContractInputGenerationWizardTest.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/RootContractInputGenerator.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/expression/FieldToContractInputMappingExpressionBuilder.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/FieldToContractInputMappingOperationBuilder.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/MappingOperationScriptBuilder.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleAggregationReferencePropertyInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleBusinessObjectQueryInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleCompositionReferencePropertyInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/NewBusinessObjectListInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/factory/BusinessObjectInitializerFactory.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/factory/InitializerFactory.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/factory/PropertyInitializerFactory.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/factory/RelationPropertyInitializerFactory.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/ui/wizard/ContractInputGenerationWizard.java

Variable of types containing composition multiple

BS-14249: support generation of script for initial value of Business

---

bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/FieldToContractInputMappingFactoryTest.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/FieldToContractInputMappingFactory.java

depth of Business Object hierarchy is higher than 5

BS-14131: Add persistenceID also on last attribute; of aggregagtion when

---

bundles/plugins/org.bonitasoft.studio.engine/src-test/java/org/bonitasoft/studio/engine/export/builder/EngineFlowElementBuilderTest.java
bundles/plugins/org.bonitasoft.studio.engine/src/org/bonitasoft/studio/engine/export/builder/AbstractProcessBuilder.java

have a working 6.x form preview

BS-14264: handle the case of not defined Iterator Expression in order to

---

bundles/plugins/org.bonitasoft.studio.designer/src-test/java/org/bonitasoft/studio/designer/core/bos/WebFormBOSArchiveFileStoreProviderTest.java
bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/core/bos/WebFormBOSArchiveFileStoreProvider.java

Fix npe when exporting a bos file containing invalid ui designer
artifacts (declared in a process but not on the file system)

BS-14071 Fix npe when exporting a bos file

---

bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/VariableNameResolverTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/AggregationReferencePropertyInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/BusinessObjectQueryInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/CompositionReferencePropertyInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleAggregationReferencePropertyInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleBusinessObjectQueryInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleCompositionReferencePropertyInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/NewBusinessObjectInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/NewBusinessObjectListInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/factory/BusinessObjectInitializerFactoryTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/factory/RelationPropertyInitializerFactoryTest.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/MappingOperationScriptBuilder.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/VariableNameResolver.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/AbstractBusinessObjectInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/AggregationReferencePropertyInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/BusinessObjectQueryInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/CompositionReferencePropertyInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleAggregationReferencePropertyInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleBusinessObjectQueryInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleCompositionReferencePropertyInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/NewBusinessObjectInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/NewBusinessObjectListInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/factory/BusinessObjectInitializerFactory.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/factory/RelationPropertyInitializerFactory.java
tests/org.bonitasoft.studio.swtbot.framework/src/org/bonitasoft/studio/swtbot/framework/BotDialog.java

Handle recursive script generation (variable naming issue)

BS-14058 Handle recursive script generation

---

bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/BonitaHomeUtil.java

Provide system properties  for custom bonita client default value of

---

bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/core/resources/RepositoryNotifier.java
bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/core/resources/WorkspaceServerResource.java
bundles/plugins/org.bonitasoft.studio.engine/src-test/java/org/bonitasoft/studio/engine/BOSEngineManagerTest.java
bundles/plugins/org.bonitasoft.studio.engine/src/org/bonitasoft/studio/engine/BOSEngineManager.java

Fix running state of engine when switching repo before first start ends

BS-14070 Fix running state of engine

---

bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/expression/FieldToContractInputMappingExpressionBuilderTest.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/expression/FieldToContractInputMappingExpressionBuilder.java

on pool : script initialization name is now init + variableName + ()
fix tests

BS-14278 Improve generated name of the initialization script

---

all-in-one/installer/installer_project_template.xml

BS-14343: Use lzma ultra compression to gain around 30Mo on each

---

bundles/plugins/org.bonitasoft.studio.engine/src-test/java/org/bonitasoft/studio/engine/TomcatVmArgsBuilderTest.java
bundles/plugins/org.bonitasoft.studio.engine/src/org/bonitasoft/studio/engine/TomcatVmArgsBuilder.java

Increase tomcat max heap space to limit engine issues when deploying

Increase tomcat max heap space

---

bundles/plugins/org.bonitasoft.studio.engine/src-test/java/org/bonitasoft/studio/engine/operation/UndeployProcessOperationTest.java
bundles/plugins/org.bonitasoft.studio.engine/src/org/bonitasoft/studio/engine/operation/DeployProcessOperation.java
bundles/plugins/org.bonitasoft.studio.engine/src/org/bonitasoft/studio/engine/operation/UndeployProcessOperation.java
bundles/plugins/org.bonitasoft.studio.form.preview/src/org/bonitasoft/studio/form/preview/FormPreviewOperation.java

Reuse undeploy logic from run operation.

BS-14269 Undeploy archived process instances before Preview

---

bundles/plugins/org.bonitasoft.studio.importer.bar/META-INF/MANIFEST.MF
bundles/plugins/org.bonitasoft.studio.importer.bar/src-test/java/org/bonitasoft/studio/importer/bar/custom/migration/ValidatorMigrationTest.java
bundles/plugins/org.bonitasoft.studio.importer.bar/src/org/bonitasoft/studio/importer/bar/custom/migration/ValidatorMigration.java

BS-14308: For Bonita Groovy Validators, the parameter return type is

---

bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/Repository.java
bundles/plugins/org.bonitasoft.studio.diagram.custom/src/org/bonitasoft/studio/diagram/custom/repository/ProcessConfigurationRepositoryStore.java

BS-14324: Local environment configurations are needed when importing

---

bundles/plugins/org.bonitasoft.studio.connectors.model.edit/src/org/bonitasoft/studio/connector/model/definition/wizard/PageComponentSwitchBuilder.java

Improve layout of list and tables in generated connector wizard pages

Improve layout of list and tables in generated connector wizard pages

---

bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/MappingOperationScriptBuilderTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/AggregationReferencePropertyInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/BusinessObjectQueryInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/CompositionReferencePropertyInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/InitializerContextTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleAggregationReferencePropertyInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleBusinessObjectQueryInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleCompositionReferencePropertyInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/NewBusinessObjectInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/operation/initializer/NewBusinessObjectListInitializerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/FieldToContractInputMapping.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/MappingOperationScriptBuilder.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/AbstractBusinessObjectInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/AggregationReferencePropertyInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/BusinessObjectQueryInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/CompositionReferencePropertyInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/IPropertyInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/InitializerContext.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleAggregationReferencePropertyInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleBusinessObjectQueryInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/MultipleCompositionReferencePropertyInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/NewBusinessObjectInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/NewBusinessObjectListInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/SimpleFieldPropertyInitializer.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/factory/AbsractInitializerFactory.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/factory/BusinessObjectInitializerFactory.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/operation/initializer/factory/RelationPropertyInitializerFactory.java

Refactor to handle a context instead of having big constructor.
Add hierarchy in Initializers to retrieve parent variable names.
:warning:  Wait 7.1.1 release before merging

BS-14131 Script generation with deep bdm.

---

platform/mirrored.target.template
platform/original_platform.target
platform/platform.target
pom.xml

- Add M2e
- Add Groovy M2e integration
- Add Spock
- Add m2 jdt connector
Mirror push on repositories.rd.lan
https://github.com/bonitasoft/bonita-internal-tools/pull/14

BS-14409 Update 7.2 target platform

---

tests/org.bonitasoft.studio.swtbot.framework/src/org/bonitasoft/studio/swtbot/framework/application/menu/AbstractBotMenu.java
tests/org.bonitasoft.studio.test.swtbot.util/src/org/bonitasoft/studio/test/swtbot/util/SWTBotTestUtil.java

BS-12100 Set focus on active shell

---

bundles/plugins/org.bonitasoft.studio.contract/messages.properties
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/ui/wizard/CreateContractInputFromBusinessObjectWizardPageTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/ui/wizard/FieldToContractInputMappingViewerCheckStateManagerTest.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/i18n/Messages.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/ui/wizard/CreateContractInputFromBusinessObjectWizardPage.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/ui/wizard/FieldToContractInputMappingViewerCheckStateManager.java

add 2 buttons select/deselect to the right of the treeViewer
add method to select/deselect all elements in the CheckStateManager
class

BS-14344 need check/uncheck all on contract generation wizard

---

bundles/features/org.bonitasoft.eclipse.platform.patch/.project
bundles/features/org.bonitasoft.eclipse.platform.patch/build.properties
bundles/features/org.bonitasoft.eclipse.platform.patch/feature.xml
bundles/features/org.bonitasoft.eclipse.platform.patch/pom.xml
bundles/features/platform-specific-feature/feature.xml
bundles/features/pom.xml
bundles/features/rootfiles-feature/feature.xml
bundles/features/studio-bos-specific-feature/feature.xml
bundles/features/studio-feature/feature.xml

iews.properties.tabbed and reuse it in Subscription

BS-14429: Use a Feature Patch to have a cleaner patching of o.e.ui.v

---

bundles/plugins/org.bonitasoft.studio.application/src/org/bonitasoft/studio/application/BonitaStudioWorkbenchAdvisor.java

Use workaround to display icons in Common Navigator

BS-14433 Display icons in Common Navigator

---

bundles/plugins/org.bonitasoft.studio.preferences/META-INF/MANIFEST.MF
bundles/plugins/org.bonitasoft.studio.preferences/src/org/bonitasoft/studio/preferences/PreferenceInitializer.java

Disable Marck occurence preference as a Workaround for a grrovy eclipse
editor issue.

BS-14434 Disable Marck occurence preference

---

bundles/plugins/org.bonitasoft.studio.tests-utils/META-INF/MANIFEST.MF
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/swt/WidgetFinder.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/swt/finder/ControlFinder.java

New SWT finder tool to easily unit test swt.

BS-14434 New SWT finder tool to easily unit test swt.

---

bundles/plugins/org.bonitasoft.studio.groovy/messages.properties
bundles/plugins/org.bonitasoft.studio.groovy/src-test/java/org/bonitasoft/studio/groovy/provider/JarExportFailedExceptionTest.java
bundles/plugins/org.bonitasoft.studio.groovy/src/org/bonitasoft/studio/groovy/Messages.java
bundles/plugins/org.bonitasoft.studio.groovy/src/org/bonitasoft/studio/groovy/provider/GroovyScriptBarResourceProvider.java
bundles/plugins/org.bonitasoft.studio.groovy/src/org/bonitasoft/studio/groovy/provider/JarExportFailedException.java

doesn't compile during bar creation.

BS-14553: Warn user when a Groovy scripts that is planned to be embedded

---

bundles/plugins/org.bonitasoft.studio.contract/messages.properties
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/i18n/Messages.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/ui/wizard/AddInputContractFromDataWizardDialog.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/ui/wizard/ContractInputGenerationWizard.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/ui/wizard/GeneratedScriptPreviewPage.java
bundles/plugins/org.bonitasoft.studio.groovy.ui/src/org/bonitasoft/studio/groovy/ui/dialog/GroovyEditorDocumentationDialogTray.java
bundles/plugins/org.bonitasoft.studio.groovy.ui/src/org/bonitasoft/studio/groovy/ui/dialog/GroovyHelpLinkFactory.java

initialization script
BS-14464 As dave I want to access groovy documentation when previewing
initialization script
-the next button is rename "preview" when user is on attribute selection page
-a link to groovy script documentation has been added
-when previewing the script and clicking ok, if user cancels pop up, he
will be rederacted to previous page and generate manually will be
selected

BS-14464 As dave I want to access groovy documentation when previewing

---

bundles/plugins/org.bonitasoft.studio.preferences/META-INF/MANIFEST.MF
bundles/plugins/org.bonitasoft.studio.preferences/src-test/java/org/bonitasoft/studio/preferences/PreferenceInitializerTest.java
bundles/plugins/org.bonitasoft.studio.preferences/src/org/bonitasoft/studio/preferences/PreferenceInitializer.java

Disable mark occurence

---

bundles/plugins/org.bonitasoft.studio-models/process.history
bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/ModelVersion.java
bundles/plugins/org.bonitasoft.studio.connectors/pom.xml
bundles/plugins/org.bonitasoft.studio.migration/src/org/bonitasoft/studio/migration/custom/migration/connector/UpdateGroovyConnectorVersionTo102.java
bundles/plugins/org.bonitasoft.studio.migration/src/org/bonitasoft/studio/migration/custom/migration/connector/UpdateTransactionalGroovyConnectorVersionTo101.java

Integrate new versions of groovy connectors
To be tested.

BS-12340  Integrate new versions of groovy connectors

---

bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/mapping/expression/FieldToContractInputMappingExpressionBuilderTest.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/mapping/expression/FieldToContractInputMappingExpressionBuilder.java
bundles/plugins/org.bonitasoft.studio.groovy.ui/src/org/bonitasoft/studio/groovy/ui/job/ComputeScriptDependenciesJob.java

Remove tmp groovy script file after dependencies resolution

BS-14451 Remove tmp groovy script file after dependencies resolution

---

bundles/plugins/org.bonitasoft.studio.common.repository/src-test/java/org/bonitasoft/studio/common/repository/store/SourceRepositoryStoreTest.java
bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/store/SourceRepositoryStore.java

Check empty collection instead of null

BS-14097 Check empty collection instead of null

---

bundles/plugins/org.bonitasoft.studio.businessobject/META-INF/MANIFEST.MF
bundles/plugins/org.bonitasoft.studio.businessobject/src-test/java/org/bonitasoft/studio/businessobject/core/operation/DeployBDMOperationTest.java
bundles/plugins/org.bonitasoft.studio.businessobject/src/org/bonitasoft/studio/businessobject/core/operation/DeployBDMOperation.java

Install BDM dependencies on deploy
https://github.com/bonitasoft/bonita-studio-sp/pull/90

BS-14390 Install BDM dependencies on deploy

---

bundles/plugins/org.bonitasoft.studio.common/messages.properties
bundles/plugins/org.bonitasoft.studio.common/src-test/java/org/bonitasoft/studio/common/jface/databinding/validator/PathValidatorTest.java
bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/Messages.java
bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/jface/databinding/validator/PathValidator.java
bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/jface/databinding/validator/TypedValidator.java
bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/jface/databinding/validator/ValidatorFactory.java

Path validator

---

bundles/plugins/org.bonitasoft.studio.engine/src-test/java/org/bonitasoft/studio/engine/operation/UndeployProcessOperationTest.java
bundles/plugins/org.bonitasoft.studio.engine/src/org/bonitasoft/studio/engine/BOSWebServerManager.java
bundles/plugins/org.bonitasoft.studio.engine/src/org/bonitasoft/studio/engine/operation/AbstractBonitaURLBuilder.java
bundles/plugins/org.bonitasoft.studio.engine/src/org/bonitasoft/studio/engine/operation/LoginUrlBuilder.java
bundles/plugins/org.bonitasoft.studio.engine/src/org/bonitasoft/studio/engine/operation/UndeployProcessOperation.java

BS-14288: Use Web rest API to delete a process definition in order to

---

bundles/plugins/org.bonitasoft.studio.actors/messages.properties
bundles/plugins/org.bonitasoft.studio.actors/src-test/java/org/bonitasoft/studio/actors/ui/editingsupport/OrganizationNameCellEditorValidatorTest.java
bundles/plugins/org.bonitasoft.studio.actors/src/org/bonitasoft/studio/actors/i18n/Messages.java
bundles/plugins/org.bonitasoft.studio.actors/src/org/bonitasoft/studio/actors/ui/editingsupport/OrganizationNameCellEditorValidator.java
bundles/plugins/org.bonitasoft.studio.actors/src/org/bonitasoft/studio/actors/ui/editingsupport/OrganizationNameEditingSupport.java

BS-14518: Avoid user to enter an invalid organization name containing

---

bundles/plugins/org.bonitasoft.studio.application/src/org/bonitasoft/studio/application/BonitaStudioWorkbenchAdvisor.java
bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/RepositoryManager.java

* Save preferences after switch (do not wait studio shutdown)
* At startup, if current repository does not exist, switch to default

BS-14450 Retrieve resposiory after crash

---

bundles/plugins/org.bonitasoft.studio.form.preview/src/org/bonitasoft/studio/form/preview/view/FormPreviewPropertiesView.java

Handle form not in process use case.

BS-14585 Legacy Form Preview with Templates

---

bundles/plugins/org.bonitasoft.studio.designer/plugin.properties
bundles/plugins/org.bonitasoft.studio.designer/plugin.xml

BS-14636: Internationalization of text for "Create new form..." proposal

---

bundles/plugins/org.bonitasoft.studio.businessobject/messages.properties
bundles/plugins/org.bonitasoft.studio.businessobject/src-test/java/org/bonitasoft/studio/businessobject/ui/wizard/control/QueryStatusLabelProviderTest.java
bundles/plugins/org.bonitasoft.studio.businessobject/src/org/bonitasoft/studio/businessobject/i18n/Messages.java
bundles/plugins/org.bonitasoft.studio.businessobject/src/org/bonitasoft/studio/businessobject/ui/wizard/control/QueriesTabItemControl.java
bundles/plugins/org.bonitasoft.studio.businessobject/src/org/bonitasoft/studio/businessobject/ui/wizard/control/QueryStatusLabelProvider.java

Add a general information message in the tab custom queries.
Add a tooltip for each multiple query without a related count query.

BS-14531, add information about count queries

---

bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/core/refactoring/RefactorContractInputOperationTest.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/core/refactoring/RefactorContractInputOperation.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/process/builders/DataBuilder.java

Contract Input Refactoring must stay at the same scope of the orignal refactored element

BS-14296 Contract Input Refactoring

---

bundles/plugins/org.bonitasoft.studio.actors/src/org/bonitasoft/studio/actors/repository/ActorFilterConfRepositoryStore.java
bundles/plugins/org.bonitasoft.studio.actors/src/org/bonitasoft/studio/actors/repository/OrganizationRepositoryStore.java
bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/store/AbstractEMFRepositoryStore.java
bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/platform/tools/CopyInputStream.java
bundles/plugins/org.bonitasoft.studio.connectors/src/org/bonitasoft/studio/connectors/repository/ConnectorConfRepositoryStore.java
bundles/plugins/org.bonitasoft.studio.diagram.custom/src/org/bonitasoft/studio/diagram/custom/repository/DiagramRepositoryStore.java
bundles/plugins/org.bonitasoft.studio.diagram.custom/src/org/bonitasoft/studio/diagram/custom/repository/ProcessConfigurationRepositoryStore.java
bundles/plugins/org.bonitasoft.studio.importer.bos/src/org/bonitasoft/studio/importer/bos/status/BosArchiveImportStatus.java

Sometimes the copy produce an empty file leading to import errors.
Try to fix it using guava copy routine and remove some useless steams

BS-14612 Improve streams management at import

---

pom.xml

Use the new version of the watchdog provided in [pull request](https://github.com/bonitasoft/bonita-studio-watchdog/pull/1)

Update watchdog version

---

bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/Repository.java
bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/core/BonitaHomeHandler.java
bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/model/IRepository.java
bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/BonitaHomeUtil.java
bundles/plugins/org.bonitasoft.studio.engine/src/org/bonitasoft/studio/engine/BOSWebServerManager.java
bundles/plugins/org.bonitasoft.studio.engine/src/org/bonitasoft/studio/engine/TomcatVmArgsBuilder.java
bundles/plugins/org.bonitasoft.studio.exporter/src/org/bonitasoft/studio/exporter/ApplicationResourcesProvider.java
bundles/plugins/org.bonitasoft.studio.preferences/src/org/bonitasoft/studio/preferences/LocaleUtil.java
tests/org.bonitasoft.studio.exporter.tests/src/org/bonitasoft/studio/exporter/tests/autologin/TestAutoLogin.java

* Add a bonita_home folder per repository
* Point that folder as bonita.home when starting tomcat
https://github.com/bonitasoft/bonita-studio-sp/pull/115

BS-14688 Use one bonita home per repository

---

bundles/plugins/org.bonitasoft.studio.expression.editor/src-test/java/org/bonitasoft/studio/expression/editor/viewer/ExpressionViewerTest.java
bundles/plugins/org.bonitasoft.studio.expression.editor/src/org/bonitasoft/studio/expression/editor/viewer/ExpressionViewer.java

BS-14768: Include Message Content Type for expression in databinding

---

bundles/plugins/org.bonitasoft.studio.designer/messages.properties
bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/ui/handler/OpenUIDesignerHandler.java

clear
Update message as it is described in comments

BS-14625 Progress information message when starting UI Designer not

---

bundles/plugins/org.bonitasoft.studio.groovy.ui/src/org/bonitasoft/studio/groovy/ui/providers/GroovyScriptExpressionEditor.java

script
if script is very simple, the job is "done" before the model has been
updated and so nothing is updated. So launch the job after the model
changed

BS-14309: Fix automatic resolution asynchronism resolution for simple

---

bundles/features/platform-specific-feature/feature.xml
bundles/features/studio-feature/feature.xml
bundles/plugins/org.bonitasoft.studio.expression.editor.win32/META-INF/MANIFEST.MF
patched-plugins/org.eclipse.gmf.runtime.lite.svg/src/org/eclipse/gmf/runtime/lite/svg/CustomSAXSVGDocumentFactory.java
patched-plugins/org.eclipse.gmf.runtime.lite.svg/src/org/eclipse/gmf/runtime/lite/svg/SVGFigure.java
pom.xml

* Always use apache SaxParser for svg

BS-11112 Update tycho to 0.22

---

bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/ui/wizard/CreateContractInputFromBusinessObjectWizardPage.java

fix button size to correctly desplay french and german in create input

---

bundles/plugins/org.bonitasoft.studio.common/messages.properties
bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/Messages.java
bundles/plugins/org.bonitasoft.studio.common/src/org/bonitasoft/studio/common/properties/Well.java
bundles/plugins/org.bonitasoft.studio.connectors.model.edit/src/org/bonitasoft/studio/connector/model/definition/wizard/ConnectorConfigurationSupport.java
bundles/plugins/org.bonitasoft.studio.connectors.model.edit/src/org/bonitasoft/studio/connector/model/definition/wizard/PageComponentSwitch.java
bundles/plugins/org.bonitasoft.studio.connectors.model.edit/src/org/bonitasoft/studio/connector/model/definition/wizard/PageComponentSwitchBuilder.java
bundles/plugins/org.bonitasoft.studio.expression.editor/src/org/bonitasoft/studio/expression/editor/viewer/ExpressionViewer.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/expression/builders/ListExpressionBuilder.java
bundles/plugins/org.bonitasoft.studio.tests-utils/src/org/bonitasoft/studio/model/expression/builders/TableExpressionBuilder.java

Add more detail link with tootltip

Improve Well widget lnf

---

bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/ui/wizard/ContractInputGenerationWizardTest.java
bundles/plugins/org.bonitasoft.studio.contract/src-test/java/org/bonitasoft/studio/contract/ui/wizard/SelectDataWizardPageTest.java
bundles/plugins/org.bonitasoft.studio.contract/src/org/bonitasoft/studio/contract/ui/wizard/SelectDataWizardPage.java

change input suffix from *_input to *Input and *_doc_input to

---

bundles/plugins/org.bonitasoft.studio.actors/src/org/bonitasoft/studio/actors/ui/wizard/connector/CustomUserInfoConnectorConfigurationWizardPage.java

add extension to organization store name

BS-14848 Actor Filter Users with Custom Information creation broken in studio

---

bundles/plugins/org.bonitasoft.studio.designer/src-test/java/org/bonitasoft/studio/designer/core/repository/NamedJSONFileStoreTest.java
bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/core/expression/FormReferenceExpressionProvider.java
bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/core/repository/InFolderJSONFileStore.java
bundles/plugins/org.bonitasoft.studio.designer/src/org/bonitasoft/studio/designer/core/repository/NamedJSONFileStore.java

List form references even with corrupted forms/pages (missing json files)
Fixes BS-15084

fix(FormMapping): List form references

---

bundles/plugins/org.bonitasoft.studio.properties/src/org/bonitasoft/studio/properties/sections/iteration/IterationPropertySection.java
bundles/plugins/org.bonitasoft.studio.properties/src/org/bonitasoft/studio/properties/sections/iteration/control/IteratorNameEditor.java

fix(UI) Multiisntantiator field

---

bundles/plugins/org.bonitasoft.studio.businessobject/messages.properties
bundles/plugins/org.bonitasoft.studio.businessobject/src/org/bonitasoft/studio/businessobject/i18n/Messages.java
bundles/plugins/org.bonitasoft.studio.businessobject/src/org/bonitasoft/studio/businessobject/ui/wizard/QueryWizardPage.java

Add a tooltip to alert that some of JPA queries format are not
supported.
fixes BS-15325

fix(BDM) Query return type guidance

---

bundles/plugins/org.bonitasoft.studio.importer/src/org/bonitasoft/studio/importer/bpmn/BPMNToProc.java

Fix a npe when importing a bpmn2 with a Text Annotation without
association.
fixes BS-15357

fix(BPMN2) Prevent npe at import

---

bundles/plugins/org.bonitasoft.studio.connectors.model.edit/messages.properties
bundles/plugins/org.bonitasoft.studio.connectors.model.edit/src/org/bonitasoft/studio/connector/model/definition/IDefinitionRepositoryStore.java
bundles/plugins/org.bonitasoft.studio.connectors.model.edit/src/org/bonitasoft/studio/connector/model/definition/dialog/AbstractDefinitionWizardDialog.java
bundles/plugins/org.bonitasoft.studio.connectors.model.edit/src/org/bonitasoft/studio/connector/model/definition/dialog/SaveConfigurationListener.java
bundles/plugins/org.bonitasoft.studio.connectors.model.edit/src/org/bonitasoft/studio/connector/model/definition/wizard/ConnectorConfiguraitonLabelProvider.java
bundles/plugins/org.bonitasoft.studio.connectors.model.edit/src/org/bonitasoft/studio/connector/model/definition/wizard/SaveConnectorConfigurationWizard.java
bundles/plugins/org.bonitasoft.studio.connectors.model.edit/src/org/bonitasoft/studio/connector/model/definition/wizard/SaveConnectorConfigurationWizardPage.java
bundles/plugins/org.bonitasoft.studio.connectors.model.edit/src/org/bonitasoft/studio/connector/model/definition/wizard/SelectConnectorConfigurationWizard.java
bundles/plugins/org.bonitasoft.studio.connectors.model.edit/src/org/bonitasoft/studio/connector/model/definition/wizard/SelectConnectorConfigurationWizardPage.java
bundles/plugins/org.bonitasoft.studio.connectors.model.edit/src/org/bonitasoft/studio/connector/model/i18n/Messages.java
tests/org.bonitasoft.studio.connectors.test/src/org/bonitasoft/studio/connectors/test/swtbot/TestLoadSaveConnectorConfiguration.java

- Retrieve dependencies in scope.
- Display a load report with missing dependencies
fixes BS-15340

fix(Connector) Load configuration with dependencies

---

bundles/plugins/org.bonitasoft.studio.actors/src-test/java/org/bonitasoft/studio/actors/operation/CleanPublishOrganizationOperationTest.java
bundles/plugins/org.bonitasoft.studio.actors/src/org/bonitasoft/studio/actors/operation/PublishOrganizationOperation.java
bundles/plugins/org.bonitasoft.studio.actors/src/org/bonitasoft/studio/actors/repository/OrganizationFileStore.java

Default attributes were not exported as xml, but xsd where expecting
them
fixes BS-15379

fix(Organization) Export default attribute in xml

---

bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/operation/ExportBosArchiveOperation.java
bundles/plugins/org.bonitasoft.studio.common.repository/src/org/bonitasoft/studio/common/repository/ui/wizard/ExportRepositoryWizardPage.java

When there is packages with sub-packages in custom connectors bos export
throw an error for duplicated zip entries

fix(Export) Bos export

---

bundles/plugins/org.bonitasoft.studio.data/src-test/java/org/bonitasoft/studio/data/ui/wizard/DataDefaultValueExpressionFilterTest.java
bundles/plugins/org.bonitasoft.studio.data/src/org/bonitasoft/studio/data/ui/wizard/DataDefaultValueExpressionFilter.java
bundles/plugins/org.bonitasoft.studio.data/src/org/bonitasoft/studio/data/ui/wizard/DataWizardPage.java

For pageflow/transient data default value only
fixes BS-15403

fix(6xForms) Enables Query expression type

---

bundles/plugins/org.bonitasoft.studio.engine/messages.properties
bundles/plugins/org.bonitasoft.studio.engine/src/org/bonitasoft/studio/engine/command/ResetEngineCommand.java
bundles/plugins/org.bonitasoft.studio.engine/src/org/bonitasoft/studio/engine/i18n/Messages.java
bundles/plugins/org.bonitasoft.studio.engine/src/org/bonitasoft/studio/engine/operation/UndeployProcessOperation.java

* Reuse the undeploy operation on all deployed process
* Display a result  popup when it fails or succeed
fixes BS-15494

fix(ResetEngine) Use undeploy operation

---

bundles/plugins/org.bonitasoft.studio.data/src-test/java/org/bonitasoft/studio/data/ui/wizard/DataDefaultValueExpressionFilterTest.java
bundles/plugins/org.bonitasoft.studio.data/src/org/bonitasoft/studio/data/ui/wizard/DataDefaultValueExpressionFilter.java
bundles/plugins/org.bonitasoft.studio.data/src/org/bonitasoft/studio/data/ui/wizard/DataWizardPage.java

For pageflow/transient data default value only
fixes [BS-15403](https://bonitasoft.atlassian.net/browse/BS-15403)

fix(6xForms) Enables Query expression type (#385)
